image: node:lts-alpine

services:
  -  postgres:13-alpine

variables:
  POSTGRES_DB: wapardev
  POSTGRES_USER: waparuser
  POSTGRES_PASSWORD: wapar-user
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - npm
  - test

npm:
  tags:
    - nodejs
  stage:  npm
  script:
    - yarn install
  cache:
    when: on_success
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

test:
  tags:
    - nodejs
  stage: test
  dependencies:
    - npm
  script:
    - yarn test:server:ci