image: node:lts-alpine

stages:
  - npm
  - test

npm:
  stage:  npm
  script:
    - npm install
  cache:
    when: on_success
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

test:
  stage: test
  dependencies:
    - npm
  script:
    - npm run test:server:ci