image: mcr.microsoft.com/devcontainers/javascript-node:0-18

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: https://docs.gitlab.com/ee/ci/services/index.html
services:
  - postgres:latest

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/

stages: # List of stages for jobs, and their order of execution
  - build
  - test

build-job: # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Installing dependencies ..."
    - yarn install
    - echo "Installation complete."

unit-test-job: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running tests..."
    - yarn test:server:ci
    - echo "Tests completed."
