image: node:lts-alpine

services:
  - postgres:13-alpine

cache:
  untracked: true
  key: dependencies
  paths:
    - node_modules/

variables:
  POSTGRES_DB: wapardev
  POSTGRES_USER: waparuser
  POSTGRES_PASSWORD: wapar-user
  POSTGRES_HOST_AUTH_METHOD: trust

test:
  tags:
    - nodejs
  before_script:
    - apk update && apk add postgresql
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "CREATE EXTENSION IF NOT EXISTS pgcrypto"
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\""
  script:
    - echo "hi"
    - yarn install --frozen-lockfile
    - yarn test:server
