image: node:lts-alpine

services:
  - postgres:13-alpine

cache:
  untracked: true
  key: dependencies
  paths:
    - node_modules/

variables:
  POSTGRES_DB: wapardev
  POSTGRES_USER: waparuser
  POSTGRES_PASSWORD: wapar-user
  POSTGRES_HOST_AUTH_METHOD: trust

test:
  tags:
    - nodejs
  script:
    - ls
    - yarn install --frozen-lockfile
    - ls
    - yarn test:server
