server:
  port: 12345
  refreshDemographicsInterval: "0 0 24 * * *" #every 24 hours
  saveDataInterval: "0 30 24 * * *" # every 30 minutes after 24 hours
  dataFilePath: "data.json"
database:
  host: postgres
  port: 5432
  name: wapar
  username: waparuser
  password: wapar-user
