name: workers-app CI

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
      - '.github/workflows/ci-workers-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**'
      - '.github/workflows/ci-workers-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile || bun install

      - name: Generate Drizzle migrations
        run: bun run db:generate

      - name: Run tests
        run: bun run test
